# Generated by Django 5.1.4 on 2025-01-10 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_uploadfilemodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadfilemodel',
            name='datahash',
            field=models.TextField(null=True),
        ),
    ]
