# Generated by Django 5.1.5 on 2025-03-15 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_uploadfilemodel_datahash'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='otp',
            field=models.IntegerField(null=True),
        ),
    ]
