# Generated by Django 3.1.12 on 2025-03-30 03:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20250329_2330'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminUserModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_id', models.CharField(max_length=10, unique=True, validators=[django.core.validators.RegexValidator(message="Admin ID must start with 'DV' followed by 8 digits.", regex='^DV\\d{8}$')])),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('otp', models.IntegerField(null=True)),
                ('is_verified', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'AdminUserModel',
            },
        ),
        migrations.DeleteModel(
            name='AdminUser',
        ),
    ]
