# Generated by Django 3.1.12 on 2025-03-31 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20250330_0834'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadfilemodel',
            name='is_duplicate',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='uploadfilemodel',
            name='similarity',
            field=models.FloatField(default=0.0),
        ),
    ]
