# Generated by Django 3.1.12 on 2025-04-02 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_auto_20250331_0724'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadfilemodel',
            name='insights_path',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
