# Generated by Django 3.1.12 on 2025-04-03 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_uploadfilemodel_insights_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadfilemodel',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected')], default='Pending', max_length=20),
        ),
    ]
