# Generated by Django 4.2.20 on 2025-04-20 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_usermodel_profile_image_alter_adminusermodel_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermodel',
            name='profile_image',
        ),
    ]
