from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('about/',views.about,name='about' ),
    path('register/', views.register, name='register'),
    path('login/', views.login, name='login'),
    #path('training/', views.training, name='training'),
    path('home/', views.home, name='home'),
    path('uploadfiles/', views.uploadfiles, name='uploadfiles'),
    path('viewfiles/', views.viewfiles, name='viewfiles'),
    path('text_to_speech/<int:id>/<str:req>/', views.text_to_speech, name='text_to_speech'),
    path('logout/', views.logout, name='logout'),
    path('forgotpass/', views.forgotpass, name='forgotpass'),
    path('resetpassword/', views.resetpassword, name='resetpassword'),
    path('profile/', views.profile, name='profile'),
    path('updateprofile/', views.updateprofile, name='updateprofile'),
    path('editprofile/', views.editprofile, name='editprofile'),
    path('sendrequest/<int:id>/', views.sendrequest, name='sendrequest'),
    path('viewrequests/', views.viewrequests, name='viewrequests'),
    path('acceptrequest/<int:id>/', views.acceptrequest, name='acceptrequest'),
    path('viewresponses/', views.viewresponses, name='viewresponses'),
    path('insight/<int:file_id>/', views.insight, name='insight'),
    path('admin_register/', views.admin_register, name='admin_register'),
    path('admina/login/', views.admina_login, name='admina_login'),
    #path("admin-dashboard/",views.admin_dashboard, name="admin_dashboard"),
    #path('admin/verify-otp/<str:admin_id>/', views.verify_admin_otp, name='verify_admin_otp'),
    path("verify-otp/", views.verify_admin_otp, name="verify_admin_otp"),
    path("verify-user-otp/", views.verify_user_otp, name="verify_user_otp"),
    path("resend-user-otp/", views.resend_user_otp, name="resend_user_otp"),
    path('check_duplicate/', views.check_duplicate, name='check_duplicate'),
    path('admina/verify-files/', views.admin_verify_files, name='admin_verify_files'),
    path('admina/approve-document/<int:id>/', views.admin_approve_document, name='admin_approve_document'),
    path("resend-otp/",views.resend_otp, name="resend_otp"),
    #path("resend-user-otp/",views.resend_user_otp, name="resend_user_otp"),
    path('admin_dashboard/',views.admin_dashboard, name='admin_dashboard'),
    path('admina/files/',views.admin_view_files, name='admin_view_files'),
    path("admina/accept-file/<int:file_id>/",views.accept_file, name="accept_file"),
    path("admina/reject-file/<int:file_id>/",views.reject_file, name="reject_file"),
    path("admina/pending-file/<int:file_id>/",views.pending_file, name="pending_file"),
    path("admin_logout",views.admin_logout,name='admin_logout'),
    path('pending-approvals/',views.pending_approvals, name='pending_approvals'),
    path('notify_users/<int:file_id>/',views.notify_users, name='notify_users'),
    path('admin-verify-files/',views.admin_verify_files, name='admin_verify_files'),
    path('admin-approve-document/<int:id>/',views.admin_approve_document, name='admin_approve_document'),
    path('admin-reject-document/<int:id>/', views.admin_reject_document, name='admin_reject_document'),
    path('admin-set-pending/<int:id>/', views.admin_set_pending, name='admin_set_pending'),
    #path('delete-file/<int:file_id>/', views.delete_file, name='delete_file'),

]
